2021-09-09 14:45:31,835 DEBUG    root            Loaded Command Group: ['gcloud', 'auth']
2021-09-09 14:45:31,907 DEBUG    root            Loaded Command Group: ['gcloud', 'auth', 'login']
2021-09-09 14:45:31,909 DEBUG    root            Running [gcloud.auth.login] with arguments: []
2021-09-09 14:45:31,930 DEBUG    requests_oauthlib.oauth2_session Generated new state btCJuWW7CG6DjavHg2Tyy2FEn8DbMo.
2021-09-09 14:45:32,135 INFO     ___FILE_ONLY___ Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=32555940559.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth&state=btCJuWW7CG6DjavHg2Tyy2FEn8DbMo&access_type=offline&code_challenge=M6SboZJ6rj2boznbMG-sbTLkZ29f9aG4kbuofz7Eyog&code_challenge_method=S256


2021-09-09 14:45:40,735 INFO     google_auth_oauthlib.flow "GET /?state=btCJuWW7CG6DjavHg2Tyy2FEn8DbMo&code=4/0AX4XfWjIMa_CBIsqPXNd5balz3FGeT7_2kFqMYGLJ0jttBrf8-1oFlswDg-ij7ECQwxXBw&scope=email%20openid%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/cloud-platform%20https://www.googleapis.com/auth/appengine.admin%20https://www.googleapis.com/auth/compute%20https://www.googleapis.com/auth/accounts.reauth&authuser=0&hd=deanware.com&prompt=consent HTTP/1.1" 200 959
2021-09-09 14:45:40,736 DEBUG    requests_oauthlib.oauth2_session Requesting url https://oauth2.googleapis.com/token using method POST.
2021-09-09 14:45:40,736 DEBUG    requests_oauthlib.oauth2_session Supplying headers {b'Accept': b'application/json', b'Content-Type': b'application/x-www-form-urlencoded;charset=UTF-8', b'user-agent': b'google-cloud-sdk gcloud/355.0.0 command/gcloud.auth.login invocation-id/ea7d97883ae14562bc0022a452f36d3f environment/None environment-version/None interactive/True from-script/False python/3.9.7 term/xterm-256color (Macintosh; Intel Mac OS X 20.5.0)'} and data {'grant_type': 'authorization_code', 'client_id': '32555940559.apps.googleusercontent.com', 'client_secret': 'ZmssLNjJy2998hD4CTg2ejr2', 'code': '4/0AX4XfWjIMa_CBIsqPXNd5balz3FGeT7_2kFqMYGLJ0jttBrf8-1oFlswDg-ij7ECQwxXBw', 'redirect_uri': 'http://localhost:8085/', 'code_verifier': 'YH8Z4a1q~RKe2i0bGV-cWnlj3SMdW2ua6bLCO28m1dGmauGTPKk.Wo2aVDbNtDj.Qsz5H.lMG9TW83_b_aELObJc.XX5R_KeIF3WaySU3nCwmUUI~jJS__fiPTFwkD_j'}
2021-09-09 14:45:40,736 DEBUG    requests_oauthlib.oauth2_session Passing through key word arguments {'json': None, 'timeout': None, 'auth': None, 'verify': True, 'proxies': None}.
2021-09-09 14:45:40,747 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): oauth2.googleapis.com:443
2021-09-09 14:46:04,848 INFO     ___FILE_ONLY___ 

Command killed by keyboard interrupt


